### ISSUE TITLE
Error: Ensure Rails environment variables are configured

### ISSUE THREAD

**Issue by AlanPadi95** [Flying-Free/ansible-role-openproject#4]
# Task

```yaml
- name: Ensure Rails environment variables are configured
  shell: |
      env RAILS_ENV="production" ./bin/rake db:create
      env RAILS_ENV="production" ./bin/rake db:migrate
      env RAILS_ENV="production" ./bin/rake db:seed
      env RAILS_ENV="production" ./bin/rake assets:precompile
  args:
    chdir: ~/openproject
  environment:
    RAILS_ENV: "production"
  become: yes
  become_user: "{{ openproject_user }}"
  become_flags: "-i"

```

# Log Error

```shell
[31m[1;35m[0m[0;31mfatal: [instance]: FAILED! => {[0m[0m
[31m[0;31m    "changed": true,[0m[0m
[31m[0;31m    "cmd": "env RAILS_ENV=\"production\" ./bin/rake db:create\nenv RAILS_ENV=\"production\" ./bin/rake db:migrate\nenv RAILS_ENV=\"production\" ./bin/rake db:seed\nenv RAILS_ENV=\"production\" ./bin/rake assets:precompile\n",[0m[0m
[31m[0;31m    "delta": "0:02:25.510457",[0m[0m
[31m[0;31m    "end": "2020-10-02 15:10:53.156311",[0m[0m
[31m[0;31m    "invocation": {[0m[0m
[31m[0;31m        "module_args": {[0m[0m
[31m[0;31m            "_raw_params": "env RAILS_ENV=\"production\" ./bin/rake db:create\nenv RAILS_ENV=\"production\" ./bin/rake db:migrate\nenv RAILS_ENV=\"production\" ./bin/rake db:seed\nenv RAILS_ENV=\"production\" ./bin/rake assets:precompile\n",[0m[0m
[31m[0;31m            "_uses_shell": true,[0m[0m
[31m[0;31m            "argv": null,[0m[0m
[31m[0;31m            "chdir": "/home/openproject/openproject",[0m[0m
[31m[0;31m            "creates": null,[0m[0m
[31m[0;31m            "executable": null,[0m[0m
[31m[0;31m            "removes": null,[0m[0m
[31m[0;31m            "stdin": null,[0m[0m
[31m[0;31m            "stdin_add_newline": true,[0m[0m
[31m[0;31m            "strip_empty_ends": true,[0m[0m
[31m[0;31m            "warn": true[0m[0m
[31m[0;31m        }[0m[0m
[31m[0;31m    },[0m[0m
[31m[0;31m    "msg": "non-zero return code",[0m[0m
[31m[0;31m    "rc": 1,[0m[0m
[31m[0;31m    "start": "2020-10-02 15:08:27.645854",[0m[0m
[31m[0;31m    "stderr": "[DEPRECATED] Bundler.environment has been removed in favor of Bundler.load (called at /home/openproject/openproject/lib/open_project/plugins/acts_as_op_engine.rb:178)\nDatabase 'openproject' already exists\n[DEPRECATED] Bundler.environment has been removed in favor of Bundler.load (called at /home/openproject/openproject/lib/open_project/plugins/acts_as_op_engine.rb:178)\n[DEPRECATED] Bundler.environment has been removed in favor of Bundler.load (called at /home/openproject/openproject/lib/open_project/plugins/acts_as_op_engine.rb:178)\n[DEPRECATED] Bundler.environment has been removed in favor of Bundler.load (called at /home/openproject/openproject/lib/open_project/plugins/acts_as_op_engine.rb:178)\nnpm run build\n\nERROR in src/app/components/datetime/timezone.service.ts(55,9): error TS2339: Property 'tz' does not exist on type 'Moment'.\nsrc/app/components/datetime/timezone.service.ts(80,23): error TS2339: Property 'tz' does not exist on type 'typeof moment'.\nsrc/app/modules/hal/dm-services/query-dm.service.ts(102,15): error TS2686: 'URI' refers to a UMD global, but the current file is a module. Consider adding an import instead.\nsrc/app/modules/hal/dm-services/query-form-dm.service.ts(89,12): error TS2686: 'URI' refers to a UMD global, but the current file is a module. Consider adding an import instead.\nsrc/app/modules/hal/dm-services/query-form-dm.service.ts(89,29): error TS2345: Argument of type '{ [key: string]: unknown; }' is not assignable to parameter of type 'boolean'.\nsrc/app/components/wp-fast-table/handlers/state/selection-transformer.ts(52,5): error TS2686: 'Mousetrap' refers to a UMD global, but the current file is a module. Consider adding an import instead.\nsrc/app/components/wp-fast-table/handlers/state/selection-transformer.ts(61,5): error TS2686: 'Mousetrap' refers to a UMD global, but the current file is a module. Consider adding an import instead.\nsrc/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts(330,5): error TS2686: 'Mousetrap' refers to a UMD global, but the current file is a module. Consider adding an import instead.\nsrc/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts(346,5): error TS2686: 'Mousetrap' refers to a UMD global, but the current file is a module. Consider adding an import instead.\nsrc/app/components/op-context-menu/handlers/op-context-menu-trigger.directive.ts(37,5): error TS2686: 'Mousetrap' refers to a UMD global, but the current file is a module. Consider adding an import instead.\nsrc/app/modules/a11y/keyboard-shortcut-service.ts(88,63): error TS2686: 'Mousetrap' refers to a UMD global, but the current file is a module. Consider adding an import instead.\nsrc/app/components/modals/export-modal/wp-table-export.modal.ts(72,15): error TS2686: 'URI' refers to a UMD global, but the current file is a module. Consider adding an import instead.\nsrc/app/components/wp-new/wp-create.controller.ts(113,25): error TS2686: 'URI' refers to a UMD global, but the current file is a module. Consider adding an import instead.\nsrc/app/components/wp-new/wp-create.controller.ts(114,26): error TS2345: Argument of type '{ back_url: URI; }' is not assignable to parameter of type 'boolean'.\nsrc/app/modules/fields/display/field-types/wp-display-spent-time-field.module.ts(57,24): error TS2686: 'URI' refers to a UMD global, but the current file is a module. Consider adding an import instead.\nsrc/app/modules/common/path-helper/path-helper.functions.ts(33,17): error TS2686: 'URI' refers to a UMD global, but the current file is a module. Consider adding an import instead.\n\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! openproject-frontend@0.1.0 build: `ng build --prod && npm run legacy-webpack`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the openproject-frontend@0.1.0 build script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/openproject/.npm/_logs/2020-10-02T15_10_53_078Z-debug.log\nrake aborted!\nFailed to compile angular frontend: 1\n/home/openproject/openproject/lib/tasks/assets.rake:66:in `block (4 levels) in <top (required)>'\n/home/openproject/openproject/lib/tasks/assets.rake:65:in `block (3 levels) in <top (required)>'\n/home/openproject/openproject/lib/tasks/assets.rake:64:in `chdir'\n/home/openproject/openproject/lib/tasks/assets.rake:64:in `block (2 levels) in <top (required)>'\nTasks: TOP => assets:precompile => assets:compile_environment => assets:prepare_op => assets:angular\n(See full trace by running task with --trace)",[0m[0m
[31m[0;31m    "stderr_lines": [[0m[0m
[31m[0;31m        "[DEPRECATED] Bundler.environment has been removed in favor of Bundler.load (called at /home/openproject/openproject/lib/open_project/plugins/acts_as_op_engine.rb:178)",[0m[0m
[31m[0;31m        "Database 'openproject' already exists",[0m[0m
[31m[0;31m        "[DEPRECATED] Bundler.environment has been removed in favor of Bundler.load (called at /home/openproject/openproject/lib/open_project/plugins/acts_as_op_engine.rb:178)",[0m[0m
[31m[0;31m        "[DEPRECATED] Bundler.environment has been removed in favor of Bundler.load (called at /home/openproject/openproject/lib/open_project/plugins/acts_as_op_engine.rb:178)",[0m[0m
[31m[0;31m        "[DEPRECATED] Bundler.environment has been removed in favor of Bundler.load (called at /home/openproject/openproject/lib/open_project/plugins/acts_as_op_engine.rb:178)",[0m[0m
[31m[0;31m        "npm run build",[0m[0m
[31m[0;31m        "",[0m[0m
[31m[0;31m        "ERROR in src/app/components/datetime/timezone.service.ts(55,9): error TS2339: Property 'tz' does not exist on type 'Moment'.",[0m[0m
[31m[0;31m        "src/app/components/datetime/timezone.service.ts(80,23): error TS2339: Property 'tz' does not exist on type 'typeof moment'.",[0m[0m
[31m[0;31m        "src/app/modules/hal/dm-services/query-dm.service.ts(102,15): error TS2686: 'URI' refers to a UMD global, but the current file is a module. Consider adding an import instead.",[0m[0m
[31m[0;31m        "src/app/modules/hal/dm-services/query-form-dm.service.ts(89,12): error TS2686: 'URI' refers to a UMD global, but the current file is a module. Consider adding an import instead.",[0m[0m
[31m[0;31m        "src/app/modules/hal/dm-services/query-form-dm.service.ts(89,29): error TS2345: Argument of type '{ [key: string]: unknown; }' is not assignable to parameter of type 'boolean'.",[0m[0m
[31m[0;31m        "src/app/components/wp-fast-table/handlers/state/selection-transformer.ts(52,5): error TS2686: 'Mousetrap' refers to a UMD global, but the current file is a module. Consider adding an import instead.",[0m[0m
[31m[0;31m        "src/app/components/wp-fast-table/handlers/state/selection-transformer.ts(61,5): error TS2686: 'Mousetrap' refers to a UMD global, but the current file is a module. Consider adding an import instead.",[0m[0m
[31m[0;31m        "src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts(330,5): error TS2686: 'Mousetrap' refers to a UMD global, but the current file is a module. Consider adding an import instead.",[0m[0m
[31m[0;31m        "src/app/components/wp-table/timeline/container/wp-timeline-container.directive.ts(346,5): error TS2686: 'Mousetrap' refers to a UMD global, but the current file is a module. Consider adding an import instead.",[0m[0m
[31m[0;31m        "src/app/components/op-context-menu/handlers/op-context-menu-trigger.directive.ts(37,5): error TS2686: 'Mousetrap' refers to a UMD global, but the current file is a module. Consider adding an import instead.",[0m[0m
[31m[0;31m        "src/app/modules/a11y/keyboard-shortcut-service.ts(88,63): error TS2686: 'Mousetrap' refers to a UMD global, but the current file is a module. Consider adding an import instead.",[0m[0m
[31m[0;31m        "src/app/components/modals/export-modal/wp-table-export.modal.ts(72,15): error TS2686: 'URI' refers to a UMD global, but the current file is a module. Consider adding an import instead.",[0m[0m
[31m[0;31m        "src/app/components/wp-new/wp-create.controller.ts(113,25): error TS2686: 'URI' refers to a UMD global, but the current file is a module. Consider adding an import instead.",[0m[0m
[31m[0;31m        "src/app/components/wp-new/wp-create.controller.ts(114,26): error TS2345: Argument of type '{ back_url: URI; }' is not assignable to parameter of type 'boolean'.",[0m[0m
[31m[0;31m        "src/app/modules/fields/display/field-types/wp-display-spent-time-field.module.ts(57,24): error TS2686: 'URI' refers to a UMD global, but the current file is a module. Consider adding an import instead.",[0m[0m
[31m[0;31m        "src/app/modules/common/path-helper/path-helper.functions.ts(33,17): error TS2686: 'URI' refers to a UMD global, but the current file is a module. Consider adding an import instead.",[0m[0m
[31m[0;31m        "",[0m[0m
[31m[0;31m        "npm ERR! code ELIFECYCLE",[0m[0m
[31m[0;31m        "npm ERR! errno 1",[0m[0m
[31m[0;31m        "npm ERR! openproject-frontend@0.1.0 build: `ng build --prod && npm run legacy-webpack`",[0m[0m
[31m[0;31m        "npm ERR! Exit status 1",[0m[0m
[31m[0;31m        "npm ERR! ",[0m[0m
[31m[0;31m        "npm ERR! Failed at the openproject-frontend@0.1.0 build script.",[0m[0m
[31m[0;31m        "npm ERR! This is probably not a problem with npm. There is likely additional logging output above.",[0m[0m
[31m[0;31m        "",[0m[0m
[31m[0;31m        "npm ERR! A complete log of this run can be found in:",[0m[0m
[31m[0;31m        "npm ERR!     /home/openproject/.npm/_logs/2020-10-02T15_10_53_078Z-debug.log",[0m[0m
[31m[0;31m        "rake aborted!",[0m[0m
[31m[0;31m        "Failed to compile angular frontend: 1",[0m[0m
[31m[0;31m        "/home/openproject/openproject/lib/tasks/assets.rake:66:in `block (4 levels) in <top (required)>'",[0m[0m
[31m[0;31m        "/home/openproject/openproject/lib/tasks/assets.rake:65:in `block (3 levels) in <top (required)>'",[0m[0m
[31m[0;31m        "/home/openproject/openproject/lib/tasks/assets.rake:64:in `chdir'",[0m[0m
[31m[0;31m        "/home/openproject/openproject/lib/tasks/assets.rake:64:in `block (2 levels) in <top (required)>'",[0m[0m
[31m[0;31m        "Tasks: TOP => assets:precompile => assets:compile_environment => assets:prepare_op => assets:angular",[0m[0m
[31m[0;31m        "(See full trace by running task with --trace)"[0m[0m
[31m[0;31m    ],[0m[0m
[31m[0;31m    "stdout": "*** Seeding for locale: 'en'\n*** Seeding basic data for standard edition\n ↳ BuiltinRolesSeeder\n   *** Skipping built in role Non member - already exists\n   *** Skipping built in role Anonymous - already exists\n ↳ RoleSeeder\n   *** Skipping roles as there are already some configured\n ↳ ActivitySeeder\n   *** Skipping activities as there are already some configured\n ↳ ColorSeeder\n   *** Skipping colors as there are already some configured\n ↳ ColorSchemeSeeder\n   *** Skipping flat colors as there are already some configured\n ↳ WorkflowSeeder\n   *** Skipping types, statuses and workflows as there are already some configured\n ↳ PrioritySeeder\n   *** Skipping priorities as there are already some configured\n ↳ SettingSeeder\n   *** Skipping settings as all settings already exist in the db\n   Loading discovered seeders: \n ↳ SettingSeeder\n   *** Skipping BasicData::Backlogs::SettingSeeder\n ↳ EnumerationsSeeder\n*** Seeding admin user\n   *** No need to seed an admin as there already is one.\n*** Seeding demo data\n ↳ ProjectSeeder\n   *** Skipping DemoData::ProjectSeeder\n   Loading discovered seeders: \n ↳ MyProjectsOverviewSeeder\n   *** Skipping DemoData::MyProjectPage::MyProjectsOverviewSeeder\n*** Loading action_view_railtie seed data\n*** Loading active_storage seed data\n*** Loading action_cable_engine seed data\n*** Loading doorkeeper_engine seed data\n*** Loading typed_dag_engine seed data\n*** Loading date_validator_engine seed data\n*** Loading ok_computer seed data\n*** Loading bourbon_engine seed data\n*** Loading i18n_js_engine seed data\n*** Loading openproject_translations seed data\n*** Loading openproject_global_roles seed data\n*** Loading openproject_auth_plugins seed data\n*** Loading openproject_auth_saml seed data\n*** Loading openproject_openid_connect seed data\n*** Loading openproject_documents seed data\n*** Loading openproject_my_project_page seed data\n*** Loading openproject_xls_export seed data\n*** Loading reportingengine seed data\n*** Loading openproject_costs seed data\n*** Loading openproject_reporting seed data\n*** Loading openproject_meeting seed data\n*** Loading openproject_pdf_export seed data\n*** Loading openproject_backlogs seed data\n*** Loading openproject_avatars seed data\n*** Loading openproject_two_factor_authentication seed data\n*** Loading openproject_webhooks seed data\n*** Loading openproject_github_integration seed data\n*** Loading openproject_ldap_groups seed data\n*** Loading grids seed data\n*** Loading my_page seed data\n*** Loading openproject_boards seed data\nLinking frontend plugins\nCleaning linked target directory /home/openproject/openproject/frontend/src/app/modules/plugins/linked\nLinking frontend of OpenProject plugin openproject-avatars to /home/openproject/openproject/frontend/src/app/modules/plugins/linked/openproject-avatars.\nLinking frontend of OpenProject plugin openproject-costs to /home/openproject/openproject/frontend/src/app/modules/plugins/linked/openproject-costs.\nLinking frontend of OpenProject plugin openproject-documents to /home/openproject/openproject/frontend/src/app/modules/plugins/linked/openproject-documents.\nLinking frontend of OpenProject plugin openproject-my_project_page to /home/openproject/openproject/frontend/src/app/modules/plugins/linked/openproject-my_project_page.\nRegenerating frontend plugin registry /home/openproject/openproject/frontend/src/app/modules/plugins/linked-plugins.module.ts.\nCleaning linked target directory /home/openproject/openproject/frontend/legacy/app/plugins\nLinking legacy frontend of OpenProject plugin openproject-costs to /home/openproject/openproject/frontend/legacy/app/plugins/openproject-costs.\nLinking legacy frontend of OpenProject plugin openproject-my_project_page to /home/openproject/openproject/frontend/legacy/app/plugins/openproject-my_project_page.\nBuilding angular frontend\n\n> openproject-frontend@0.1.0 prebuild /home/openproject/openproject/frontend\n> ./scripts/link_plugin_placeholder.js\n\n\n> openproject-frontend@0.1.0 build /home/openproject/openproject/frontend\n> ng build --prod && npm run legacy-webpack\n\n\nDate: 2020-10-02T15:10:52.975Z\nHash: c950a2fe572d45f574d8\nTime: 22820ms\nchunk {0} runtime.e78c12df505814cde2c7.js (runtime) 1.43 kB [entry] [rendered]\nchunk {1} main.afd6651dfda78b252126.js (main) 128 bytes [initial] [rendered]\nchunk {2} polyfills.5d563896d0a5c2366caa.js (polyfills) 130 bytes [initial] [rendered]\nchunk {3} styles.a84b11287d310dea38c9.css (styles) 45.8 kB [initial] [rendered]",[0m[0m
[31m[0;31m    "stdout_lines": [[0m[0m
[31m[0;31m        "*** Seeding for locale: 'en'",[0m[0m
[31m[0;31m        "*** Seeding basic data for standard edition",[0m[0m
[31m[0;31m        " ↳ BuiltinRolesSeeder",[0m[0m
[31m[0;31m        "   *** Skipping built in role Non member - already exists",[0m[0m
[31m[0;31m        "   *** Skipping built in role Anonymous - already exists",[0m[0m
[31m[0;31m        " ↳ RoleSeeder",[0m[0m
[31m[0;31m        "   *** Skipping roles as there are already some configured",[0m[0m
[31m[0;31m        " ↳ ActivitySeeder",[0m[0m
[31m[0;31m        "   *** Skipping activities as there are already some configured",[0m[0m
[31m[0;31m        " ↳ ColorSeeder",[0m[0m
[31m[0;31m        "   *** Skipping colors as there are already some configured",[0m[0m
[31m[0;31m        " ↳ ColorSchemeSeeder",[0m[0m
[31m[0;31m        "   *** Skipping flat colors as there are already some configured",[0m[0m
[31m[0;31m        " ↳ WorkflowSeeder",[0m[0m
[31m[0;31m        "   *** Skipping types, statuses and workflows as there are already some configured",[0m[0m
[31m[0;31m        " ↳ PrioritySeeder",[0m[0m
[31m[0;31m        "   *** Skipping priorities as there are already some configured",[0m[0m
[31m[0;31m        " ↳ SettingSeeder",[0m[0m
[31m[0;31m        "   *** Skipping settings as all settings already exist in the db",[0m[0m
[31m[0;31m        "   Loading discovered seeders: ",[0m[0m
[31m[0;31m        " ↳ SettingSeeder",[0m[0m
[31m[0;31m        "   *** Skipping BasicData::Backlogs::SettingSeeder",[0m[0m
[31m[0;31m        " ↳ EnumerationsSeeder",[0m[0m
[31m[0;31m        "*** Seeding admin user",[0m[0m
[31m[0;31m        "   *** No need to seed an admin as there already is one.",[0m[0m
[31m[0;31m        "*** Seeding demo data",[0m[0m
[31m[0;31m        " ↳ ProjectSeeder",[0m[0m
[31m[0;31m        "   *** Skipping DemoData::ProjectSeeder",[0m[0m
[31m[0;31m        "   Loading discovered seeders: ",[0m[0m
[31m[0;31m        " ↳ MyProjectsOverviewSeeder",[0m[0m
[31m[0;31m        "   *** Skipping DemoData::MyProjectPage::MyProjectsOverviewSeeder",[0m[0m
[31m[0;31m        "*** Loading action_view_railtie seed data",[0m[0m
[31m[0;31m        "*** Loading active_storage seed data",[0m[0m
[31m[0;31m        "*** Loading action_cable_engine seed data",[0m[0m
[31m[0;31m        "*** Loading doorkeeper_engine seed data",[0m[0m
[31m[0;31m        "*** Loading typed_dag_engine seed data",[0m[0m
[31m[0;31m        "*** Loading date_validator_engine seed data",[0m[0m
[31m[0;31m        "*** Loading ok_computer seed data",[0m[0m
[31m[0;31m        "*** Loading bourbon_engine seed data",[0m[0m
[31m[0;31m        "*** Loading i18n_js_engine seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_translations seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_global_roles seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_auth_plugins seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_auth_saml seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_openid_connect seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_documents seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_my_project_page seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_xls_export seed data",[0m[0m
[31m[0;31m        "*** Loading reportingengine seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_costs seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_reporting seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_meeting seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_pdf_export seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_backlogs seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_avatars seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_two_factor_authentication seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_webhooks seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_github_integration seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_ldap_groups seed data",[0m[0m
[31m[0;31m        "*** Loading grids seed data",[0m[0m
[31m[0;31m        "*** Loading my_page seed data",[0m[0m
[31m[0;31m        "*** Loading openproject_boards seed data",[0m[0m
[31m[0;31m        "Linking frontend plugins",[0m[0m
[31m[0;31m        "Cleaning linked target directory /home/openproject/openproject/frontend/src/app/modules/plugins/linked",[0m[0m
[31m[0;31m        "Linking frontend of OpenProject plugin openproject-avatars to /home/openproject/openproject/frontend/src/app/modules/plugins/linked/openproject-avatars.",[0m[0m
[31m[0;31m        "Linking frontend of OpenProject plugin openproject-costs to /home/openproject/openproject/frontend/src/app/modules/plugins/linked/openproject-costs.",[0m[0m
[31m[0;31m        "Linking frontend of OpenProject plugin openproject-documents to /home/openproject/openproject/frontend/src/app/modules/plugins/linked/openproject-documents.",[0m[0m
[31m[0;31m        "Linking frontend of OpenProject plugin openproject-my_project_page to /home/openproject/openproject/frontend/src/app/modules/plugins/linked/openproject-my_project_page.",[0m[0m
[31m[0;31m        "Regenerating frontend plugin registry /home/openproject/openproject/frontend/src/app/modules/plugins/linked-plugins.module.ts.",[0m[0m
[31m[0;31m        "Cleaning linked target directory /home/openproject/openproject/frontend/legacy/app/plugins",[0m[0m
[31m[0;31m        "Linking legacy frontend of OpenProject plugin openproject-costs to /home/openproject/openproject/frontend/legacy/app/plugins/openproject-costs.",[0m[0m
[31m[0;31m        "Linking legacy frontend of OpenProject plugin openproject-my_project_page to /home/openproject/openproject/frontend/legacy/app/plugins/openproject-my_project_page.",[0m[0m
[31m[0;31m        "Building angular frontend",[0m[0m
[31m[0;31m        "",[0m[0m
[31m[0;31m        "> openproject-frontend@0.1.0 prebuild /home/openproject/openproject/frontend",[0m[0m
[31m[0;31m        "> ./scripts/link_plugin_placeholder.js",[0m[0m
[31m[0;31m        "",[0m[0m
[31m[0;31m        "",[0m[0m
[31m[0;31m        "> openproject-frontend@0.1.0 build /home/openproject/openproject/frontend",[0m[0m
[31m[0;31m        "> ng build --prod && npm run legacy-webpack",[0m[0m
[31m[0;31m        "",[0m[0m
[31m[0;31m        "",[0m[0m
[31m[0;31m        "Date: 2020-10-02T15:10:52.975Z",[0m[0m
[31m[0;31m        "Hash: c950a2fe572d45f574d8",[0m[0m
[31m[0;31m        "Time: 22820ms",[0m[0m
[31m[0;31m        "chunk {0} runtime.e78c12df505814cde2c7.js (runtime) 1.43 kB [entry] [rendered]",[0m[0m
[31m[0;31m        "chunk {1} main.afd6651dfda78b252126.js (main) 128 bytes [initial] [rendered]",[0m[0m
[31m[0;31m        "chunk {2} polyfills.5d563896d0a5c2366caa.js (polyfills) 130 bytes [initial] [rendered]",[0m[0m
[31m[0;31m        "chunk {3} styles.a84b11287d310dea38c9.css (styles) 45.8 kB [initial] [rendered]"[0m[0m
[31m[0;31m    ][0m[0m
[31m[0;31m}[0m[0m
[31m[0;31m[0m[0m
[31mERROR: [0m

```

**Comment by AlanPadi95** [comment]
#### Log for file `/home/openproject/.npm/_logs/2020-10-07T11_28_23_381Z-debug.log`:

```shell
0 info it worked if it ends with ok
1 verbose cli [ '/home/openproject/.nodenv/versions/8.12.0/bin/node',
1 verbose cli   '/home/openproject/.nodenv/versions/8.12.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle openproject-frontend@0.1.0~prebuild: openproject-frontend@0.1.0
6 verbose lifecycle openproject-frontend@0.1.0~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle openproject-frontend@0.1.0~prebuild: PATH: /home/openproject/.nodenv/versions/8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/openproject/openproject/frontend/node_modules/.bin:/home/openproject/.nodenv/versions/8.12.0/bin:/home/openproject/.nodenv/libexec:/home/openproject/.nodenv/plugins/node-build/bin:/home/openproject/openproject/vendor/bundle/ruby/2.6.0/bin:/home/openproject/.rbenv/versions/2.6.1/bin:/home/openproject/.rbenv/libexec:/home/openproject/.rbenv/plugins/ruby-build/bin:/home/openproject/.nodenv/shims:/home/openproject/.nodenv/bin:/home/openproject/.rbenv/shims:/home/openproject/.rbenv/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/home/openproject/.local/bin:/home/openproject/bin
8 verbose lifecycle openproject-frontend@0.1.0~prebuild: CWD: /home/openproject/openproject/frontend
9 silly lifecycle openproject-frontend@0.1.0~prebuild: Args: [ '-c', './scripts/link_plugin_placeholder.js' ]
10 silly lifecycle openproject-frontend@0.1.0~prebuild: Returned: code: 0  signal: null
11 info lifecycle openproject-frontend@0.1.0~build: openproject-frontend@0.1.0
12 verbose lifecycle openproject-frontend@0.1.0~build: unsafe-perm in lifecycle true
13 verbose lifecycle openproject-frontend@0.1.0~build: PATH: /home/openproject/.nodenv/versions/8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/openproject/openproject/frontend/node_modules/.bin:/home/openproject/.nodenv/versions/8.12.0/bin:/home/openproject/.nodenv/libexec:/home/openproject/.nodenv/plugins/node-build/bin:/home/openproject/openproject/vendor/bundle/ruby/2.6.0/bin:/home/openproject/.rbenv/versions/2.6.1/bin:/home/openproject/.rbenv/libexec:/home/openproject/.rbenv/plugins/ruby-build/bin:/home/openproject/.nodenv/shims:/home/openproject/.nodenv/bin:/home/openproject/.rbenv/shims:/home/openproject/.rbenv/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/home/openproject/.local/bin:/home/openproject/bin
14 verbose lifecycle openproject-frontend@0.1.0~build: CWD: /home/openproject/openproject/frontend
15 silly lifecycle openproject-frontend@0.1.0~build: Args: [ '-c', 'ng build --prod && npm run legacy-webpack' ]
16 silly lifecycle openproject-frontend@0.1.0~build: Returned: code: 1  signal: null
17 info lifecycle openproject-frontend@0.1.0~build: Failed to exec build script
18 verbose stack Error: openproject-frontend@0.1.0 build: `ng build --prod && npm run legacy-webpack`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/home/openproject/.nodenv/versions/8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at EventEmitter.emit (events.js:214:7)
18 verbose stack     at ChildProcess.<anonymous> (/home/openproject/.nodenv/versions/8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at ChildProcess.emit (events.js:214:7)
18 verbose stack     at maybeClose (internal/child_process.js:915:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
19 verbose pkgid openproject-frontend@0.1.0
20 verbose cwd /home/openproject/openproject/frontend
21 verbose Linux 4.19.76-linuxkit
22 verbose argv "/home/openproject/.nodenv/versions/8.12.0/bin/node" "/home/openproject/.nodenv/versions/8.12.0/bin/npm" "run" "build"
23 verbose node v8.12.0
24 verbose npm  v6.4.1
25 error code ELIFECYCLE
26 error errno 1
27 error openproject-frontend@0.1.0 build: `ng build --prod && npm run legacy-webpack`
27 error Exit status 1
28 error Failed at the openproject-frontend@0.1.0 build script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

```

**Comment by AlanPadi95** [comment]
## SOLVED

Changes OpenProject, Node and Ruby versions in order to keep the application up tu date
